---
title: "Vantage Pro 2 Weather Station Data"
author: "Valeria Aspinall"
date: "2026-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
# Packages ------------------------------------------
library(knitr)
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(tidyverse)
library(data.table)
library(grid)
library(gridExtra)
```

### 2025 Master Function to Clean, Organize and Identify Gaps
```{r}
#1. start by uploading the data for each month of data from Vantage Pro
files25_vantage <- c(
  # June 2025 
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-06.csv",
  # July 2025
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-07.csv",
  # August 2025
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-08.csv",
  # September 2025
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-09.csv",
  # October 2025 
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-10.csv", 
  # November 2025
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-11.csv", 
  #December 2025
  "/Users/valeriaaspinall/Desktop/UGA Thesis Project /R Work - Thesis/Celeste Thesis/vantage_data/2025-12.csv"
)

#2a. in order to identify implicit and explicit missing values, create 'empty' data frames for each month at 15min intervals, by defining the start and end DateTimes for each.

starts <- as.POSIXct(c("2025-06-01 00:15:00", "2025-07-01 00:15:00", "2025-08-01 00:15:00", "2025-09-01 00:15:00", "2025-10-01 00:15:00", "2025-11-01 00:15:00", "2025-12-01 00:15:00"))
ends <- as.POSIXct(c("2025-07-01 00:00:00", "2025-08-01 00:00:00", "2025-09-01 00:00:00", "2025-10-01 00:00:00", "2025-11-01 00:00:00", "2025-12-01 00:00:00", "2026-01-01 00:00:00"))
month_names <- c("June 2025", "July 2025", "August 2025", "September 2025", "October 2025", "Novemeber 2025", "December 2025")

#3a. create the combined column names due to there being two metadata rows, using june as a template, replace the --- values with NA, and since I am using the read_csv vs. the read.csv, watch out for the text used
hdr <- read_csv(files25_vantage[1], na = c("", "---"), n_max =2, col_names = FALSE)
#3b. create a column names function that merges the two together: cols 
col_names <- paste(hdr[1, ], hdr[2, ], sep = "_")

#4a. Create a master function that cleans, expands and summarizes the data in three steps A,B,C 
process_month <- function(path, m_name, start_t, end_t) { #file location, name of the month above, when month should start and end
  #Step A: initial data reading and cleaning 
  df <- read_csv(path, na = c("", "---"), skip = 2, col_names = col_names, show_col_types = FALSE) %>%
     mutate(DateTime = dmy_hms(paste(NA_Date, NA_Time)),
            DateTime = force_tz(as.POSIXct(DateTime), tzone = "America/Costa_Rica")) %>%
    select(DateTime, everything(), -NA_Date, -NA_Time)
  #Step B: identify missing values by expanding to the full month range created above 
  master_df <- data.frame(DateTime = seq(from = start_t, to = end_t, by = "15 min")) %>%
      mutate(DateTime = force_tz(DateTime, tzone = "America/Costa_Rica"))
  final_df <- master_df %>% 
    left_join(df, by = "DateTime")
  #Step C: identify gaps (using Out_Hum as the reference variable)
    gap_summary <- final_df %>% 
      mutate(is_missing = is.na(Out_Hum)) %>%
      mutate(gap_id = rleid(is_missing)) %>% 
      filter(is_missing == TRUE) %>%
      group_by(gap_id) %>%
      summarise(
        start_time = min(DateTime),
        end_time = max(DateTime), 
        duration_hours = as.numeric(difftime(max(DateTime), min(DateTime), units = "hours")) + 0.25,
        .groups = 'drop'
      )
    return(list(data = final_df, gaps = gap_summary, label = m_name, start = start_t, end = end_t))
}

#5a. execute the above master function as a batch process for all the months 
processed_25months <- mapply(process_month, 
                                path = files25_vantage, 
                                m_name = month_names, 
                                start_t = starts, 
                                end_t = ends, 
                                SIMPLIFY = FALSE)
#5b. extract back into the global environment, and perhaps check each data frame thoroughly
final_dfs <- lapply(processed_25months, `[[`, "data")
names(final_dfs) <- month_names
list2env(final_dfs, envir = .GlobalEnv)
```

### Master Function for Plotting the Missing Data
```{r}
# ----------- Functions - Explanation Start ----------- 
# When we use functions (), what goes inside is called a place holder. In this case month_result. This is called a 'formal parameter'. I am basically telling R = I will give you a piece of data later, while working inside this function, call that piece of data 'month_result. 

# The data arrives later, with the lapply function below in step 2, and using the information from the master cleaning, organizing and gap ID workflow above. The list returns with gaps = gap_summary, label = m_name, start = start_t, end = end_t, which are used below. 
# ----------- Functions - Explanation End ------------

#1a. create a master function to generate the gap plot for a single month's results
make_gap_plot <- function(month_result) {
  # identify and extract the components of your list that will go in the plot 
  df_gaps <- month_result$gaps
  m_label <- month_result$label
  start_t <- month_result$start
  end_t   <- month_result$end
  # build the ggplot code using the whole month and plotting the gaps within
  p25 <- ggplot(df_gaps) +
    # the background segment represents the full intended month
    annotate("segment", x = start_t, xend = end_t, y = 1, yend = 1, 
             color = "grey80", size = 2) +
    #adding code to point the start and end of each month 
    annotate("segment", x = start_t, xend = start_t, y = 0.9, yend = 1.1, 
             color = "grey10", size = 0.5) +
    annotate("segment", x = end_t, xend = end_t, y = 0.9, yend = 1.1, 
             color = "grey10", size = 0.5) +
    # the red segments are for identified time gaps in the data 
    geom_segment(aes(x = start_time, xend = end_time, y = 1, yend = 1), 
                 color = "red", size = 6) +
    # format the x-axis with date labels
    scale_x_datetime(date_breaks = "2 days", date_labels = "%b %d") + #%b Feb, Mar; %d 01, 28 
    theme_minimal() +
    labs(
      title = paste("Missing Data Gaps:", m_label),
      subtitle = "Red bars indicate time periods of missing data",
      x = "Date",
      y = ""
    ) +
    # this cleans up the Y-axis, which is not necessary in this 1D graph 
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank()
    )
  return(p25)
}

#2. this is the code that causes the data "arrival" and it creates a list of ggplots 
gap_plots_list <- lapply(processed_25months, make_gap_plot)

#3. view the individual plots by changing [[#]] (example: June)
gap_plots_list[[1]]

# 4. this code saves all plots as separate png files automatically using a for loop 
for (i in seq_along(gap_plots_list)) {
  m_name <- processed_25months[[i]]$label
  ggsave(filename = paste("gap_plot_", m_name, ".png"), 
         plot = gap_plots_list[[i]], width = 10, height = 3)
}

#5. plotting all the graphs in one figure that fits a word document, each one in a row 

#5a. clean the titles and subtitles of the individual plots by batch
clean_plots <- lapply(gap_plots_list, function(p) {
  current_title <- p$label$title
  new_title <- gsub("Missing Data Gaps: ", "", current_title) # new, gsub 
  p +
    labs(title = new_title, subtitle = NULL, y = NULL, x = NULL) +
    theme (
      plot.title = element_text(size = 10),
      panel.border = element_rect(color = "gray10", fill = NA, size = 0.5))
     #plot.background = element_rect(color = "grey10", fill = NA, size = 0.5))
})

fig1_gap_plots <- grid.arrange(
  grobs = clean_plots,
  nrow = 7, 
  ncol = 1, 
  top = textGrob("2025 Vantage Pro 2 Monthly Data Gaps", 
                 gp = gpar(fontsize = 18, fontface = "bold")),
  bottom = textGrob("Fig 1. Visualizing missing weather station data by month for 2025, red bars indicate missing time periods.", gp = gpar(fontsize = 12, fontface = "italic")))

# using ggsave allows you to export the figure as a png for easier use
ggsave("2025_DataGaps.png", fig1_gap_plots,
       width = 9,
       height = 12,
       units = "in", # inches obvio 
       dpi = 300 # dots per incn, print quality
       )
```
